### ISSUE TITLE
Have you considered storing csv's generated by G4ELM's utility (exe)

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [vk2kvp/GD77-codeplug#1]
You could use the utility (windows exe) by G4ELM that does Codeplug.dat <----> spreadsheets (csv) e.g. Zones.csv, Channels.csv, Contacts.csv, and Groups.csv

Then you can put the csv speadsheets in github, which would allow PR's to be managed as these are just plain text files

**Comment by vk2kvp** [comment]
Roger, refer to the ZIP file GD77-All_AU_Codeplug_v0.6_csv.zip

**Comment by vk2kvp** [comment]
Sorry, did not fully understand your previous comment. I like the idea of letting github track the revisions which could be better done by replacing the text files.

**Comment by rogerclarkmelbourne** [comment]
See www.gb3gf.co.uk/downloads.html

BTW. I am in contact with Colin G4EML who wrote the utility, as he contributes to my CPS.

If I had time I'd try to add that feature to my CPS, but I don't have the time, and Colin's code is not written in C# so would be difficult to migrate across, even if I had a copy of it.

**Comment by vk2kvp** [comment]
I have added the CSV files for the MD380-390 code plug on https://github.com/vk2kvp/md380-codeplug and will include the corresponding ones for the GD77 in the next release.

**Comment by rogerclarkmelbourne** [comment]
OK
